import utils

# Container 1A (mm and kg)
CONTAINER_WIDTH = 587
CONTAINER_HEIGHT = 233
CONTAINER_DEPTH = 220
CONTAINER_LOAD = 500000

# Pallet EUR 1 (mm and kg)
PALLET_WIDTH = 587
PALLET_DEPTH = 233
PALLET_HEIGHT = 220
PALLET_LOAD = 500000
PALLET_DIMS = utils.Dimension(PALLET_WIDTH, PALLET_DEPTH, PALLET_HEIGHT, PALLET_LOAD)

# Product dimension ranges (mm and kg)
NUM_PRODUCTS = int(1e6)
MIN_PRODUCT_WIDTH = 50
MAX_PRODUCT_WIDTH = PALLET_WIDTH
MIN_PRODUCT_DEPTH = 50
MAX_PRODUCT_DEPTH = PALLET_DEPTH
MIN_PRODUCT_HEIGHT = 50
MAX_PRODUCT_HEIGHT = PALLET_HEIGHT
MIN_PRODUCT_WEIGHT = 2
MAX_PRODUCT_WEIGHT = PALLET_LOAD

# Numpy
RANDOM_SEED = 42
